// Generated by CoffeeScript 1.6.3
define(["jquery", "shared/classes/managers/view.manager", "shared/classes/globals.class", "jqueryui"], function($, ViewManager, Globals) {
  return $(function() {
    console.log("App initializing...");
    Globals.initialize();
    return require(["jqte"], function() {
      $(".editor").jqte();
      return console.log("App initialized!");
    });
  });
});
